### ISSUE TITLE
Support cyrillic and other non latin languages, uppercase not detected

### ISSUE THREAD

**Issue by pethers** [vt-middleware/passay#100]
private final PasswordValidator passwordValidator = new PasswordValidator(new LengthRule(8, 64),			new CharacterRule(EnglishCharacterData.UpperCase, 1), new CharacterRule(EnglishCharacterData.LowerCase, 1),
			new CharacterRule(EnglishCharacterData.Digit, 1), new CharacterRule(EnglishCharacterData.Special, 1),
			new WhitespaceRule());

Sample password : ЭтотестРомен1!

will get error in validation 

valid=false,details=[INSUFFICIENT_UPPERCASE:{minimumRequired=1, matchingCharacterCount=0, validCharacters=ABCDEFGHIJKLMNOPQRSTUVWXYZ, matchingCharacters=}, INSUFFICIENT_LOWERCASE:{minimumRequired=1, matchingCharacterCount=0, validCharacters=abcdefghijklmnopqrstuvwxyz, matchingCharacters=}],metadata=counts={UpperCase=0, Special=1, Digit=1, LowerCase=0, Length=14, Whitespace=0}

Java works well with toLowerCase,toUpperCase and isUpperCase, 

Sample code
[CyrillicTest.txt](https://github.com/vt-middleware/passay/files/3161969/CyrillicTest.txt)

**Comment by pethers** [comment]
Fixed with custom implementation CharacterData interface.

**Comment by dfish3r** [comment]
If you have an implementation of `CharacterData` that you think is generally useful, feel free to open a PR to contribute. Thanks.
