### ISSUE TITLE
No Updated Example!!

### ISSUE THREAD

**Issue by DheerajKN** [vt-middleware/passay#101]
I am fascinated by the Passay project and really loved it. But the only example that I find online is the Baeldung's: https://www.baeldung.com/registration-password-strength-and-rules which is developed using passay version 1.0 and most of the functions are depreciated in the next version. 
```
  PasswordValidator validator = new PasswordValidator(Arrays.asList(
           new LengthRule(8, 30), 
           new UppercaseCharacterRule(1), 
           new DigitCharacterRule(1), 
           new SpecialCharacterRule(1), 
           new NumericalSequenceRule(3,false), 
           new AlphabeticalSequenceRule(3,false), 
           new QwertySequenceRule(3,false),
           new WhitespaceRule()));
```
But I was able to get equivalent functions for version 1.3.1
```
 new UppercaseCharacterRule(1), ->  new CharacterRule(EnglishCharacterData.UpperCase, 1), 
 new DigitCharacterRule(1), -> new CharacterRule(EnglishCharacterData.UpperCase, 1), 
 new SpecialCharacterRule(1), -> new CharacterRule(EnglishCharacterData.UpperCase, 1), 
```

So for those familiar with passay can you help me with equivalent functions in version 1.3.1 for:

```
 new NumericalSequenceRule(3,false), 
 new AlphabeticalSequenceRule(3,false), 
 new QwertySequenceRule(3,false),
```

**Comment by dfish3r** [comment]
I took a pass over the documentation for the 1.6.0 release. Updated for new rules and add a few more examples.
