### ISSUE TITLE
Need support to prevent/allow incrementing/decrementing series of numbers and letters

### ISSUE THREAD

**Issue by victropolis** [vt-middleware/passay#104]
Need support to prevent/allow two or more characters that are incrementing/decrementing series of numbers and letters.  (eg. 123, 987, abc, xyz, etc.) . Thanks!

**Comment by dfish3r** [comment]
Take a look at `IllegalSequenceRule`.

**Comment by EvanFriday** [comment]
`IllegalSequenceRule` supports sequences of characters. It does not support a regex unless I am missing something on http://www.passay.org/javadocs/org/passay/CharacterSequence.html

Creating a list of all possible incrementing / decrementing sequences is not a feasible solution.

**Comment by dfish3r** [comment]
If you could provide a test case for a password that should fail it would help provide a basis for further discussion. I *think* I know what you're asking for, but I'm not certain.

**Comment by victropolis** [comment]
@dfish3r working on unit test now

**Comment by victropolis** [comment]
@dfish3r it looks like we may be able to do what we need with a `new IllegalSequenceRule(EnglishSequenceData.Numerical, N, false)` and a `new IllegalSequenceRule(EnglishSequenceData.Alphanumeric, N, false)` where N is the sequence length we're validating against.    @EvanFriday

**Comment by dfish3r** [comment]
Reporter found a solution. Reopen if necessary.
