### ISSUE TITLE
Error during dependency download

### ISSUE THREAD

**Issue by rmanenti** [vt-middleware/passay#120]
Hello,
   
   I have added Passay to my project, but when I try to download its dependencies from maven, the following error occurs.

`Failed to execute goal on project -----: Could not resolve dependencies for project------:war:1.0: Failed to collect dependencies at org.passay:passay:jar:1.6.0: Failed to read artifact descriptor for org.passay:passay:jar:1.6.0: Could not transfer artifact org.passay:passay:pom:1.6.0 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version -> [Help 1]`

Could you please help?

Best regards.

**Comment by dfish3r** [comment]
For some reason your version of java isn't using a TLS protocol version that is supported by maven central.

See https://stackoverflow.com/questions/50824789/why-am-i-getting-received-fatal-alert-protocol-version-or-peer-not-authentic
