### ISSUE TITLE
Provide a release description/changelog

### ISSUE THREAD

**Issue by famod** [vt-middleware/passay#131]
Nice lib, thanks!

It would be helpful if there was a description per release: https://github.com/vt-middleware/passay/releases
When "drafting" one, GH even offers to generate a description for you.

**Comment by dfish3r** [comment]
The changelog is documented on the web site: https://www.passay.org/download.html
We just haven't been keen on doing it in two places, but admittedly I haven't looked at how easy/hard it is to use the github feature.

**Comment by famod** [comment]
Huh, how did I miss that? 🤔 So it might be enough to just link to from GH.

**Comment by dfish3r** [comment]
Added a release in github with a pointer to the download page.
