### ISSUE TITLE
Want to create a typescript version of this library

### ISSUE THREAD

**Issue by CodingSpiderFox** [vt-middleware/passay#138]
I recently had to implement a password policy enforcement in TS

Would it have been Java I know what I would have chosen: passay :)

I was thinking about porting it to TS so that people coming to TS from the Java ecosystem.
Would that be OK for you as the inventors of passay?

What do you think about the idea?

**Comment by dfish3r** [comment]
Our licensing terms allow this if you give credit. So yeah, you're welcome to create a TS version of the same name.

**Comment by CodingSpiderFox** [comment]
Thanks a lot :)
