### ISSUE TITLE
Problems with org.passay.GermanSequenceData in 1.6.5

### ISSUE THREAD

**Issue by MasterGenny41** [vt-middleware/passay#163]
The enum cannot be used because the values crash while initialization of DEQwertz.
The used character sequences have different length and this throws exception, so this version is not useful.

There is a difference to 1.6.4 with an additional 'ß'
Length 14 > ^1234567890ß\´
Length 13 > °!"§$%&/()=?`

I think it was a try to add the 'ß' instead of the '\\', you need to remove the 'ß' or the '\\' to get a valid length for instantiating.

**Comment by dfish3r** [comment]
Fixed in 118c330dd770ae145e7fdb0747eb3990b90aa4a6
