### ISSUE TITLE
Incorrect sentences in "passay.properties"

### ISSUE THREAD

**Issue by autumoswitzerland** [vt-middleware/passay#165]
In 

https://github.com/vt-middleware/passay/blob/main/src/main/resources/passay.properties

there are effectively words missing in the sentences. So the sentences make no sense!

Examples:
-----------
Password %2$s the illegal character '%1$s'.
- > should be:
Password %2$s contains the illegal character '%1$s'.

Password %2$s the user id '%1$s'.
- > should be:
Password %2$s contains the user id '%1$s'.

There are more! It seems the word 'contain' is missing often.

**Comment by dfish3r** [comment]
Different rules use different message syntax. `IllegalCharacterRule` includes the illegal character at %1 and the match behavior at %2. So the string replacement does create a string with proper english grammar.

See https://github.com/vt-middleware/passay/blob/main/src/test/java/org/passay/IllegalCharacterRuleTest.java#L81

**Comment by autumoswitzerland** [comment]
Uff, missed that. Thanks for clarification and my apologies!

**Comment by autumoswitzerland** [comment]
Closed
