### ISSUE TITLE
Compile for Java 1.6

### ISSUE THREAD

**Issue by KangoV** [vt-middleware/passay#26]
There seems that would be a few minor code changes to make this compatible with 1.6. The main ones are the diamond (<>) operator, strings in a coupld of switch statements and the resources in a try () { clause.

I've made these changes myself and hit no errors at all. I could push the changes, but never used github before.  If someone could help ... ;)

**Comment by KangoV** [comment]
Please ignore this. Upon further inspection, it would be quite an onerous task to backport to 1.6.

**Comment by dfish3r** [comment]
Closed at submitters request.
