### ISSUE TITLE
Ussing passay with JDK 1.6

### ISSUE THREAD

**Issue by acevedodamian** [vt-middleware/passay#29]
Hi guys, you've made a great job with this library , i'm using it for password validations and policies, and it's really useful. The problem is now i need to use it with JDK 1.6, ( customer requirement ) i've tried to compile with 1.6, but i got a lot of: 
"'<>' operator is not allowed for source level below 1.7"
do you have any suggestion ?

keep up with the great work,
regards
Damian

**Comment by acevedodamian** [comment]
theres anyway i can get sources 1.0 version  ?  

thanks

**Comment by dfish3r** [comment]
It's available in github: https://github.com/vt-middleware/passay/tree/v1.0

**Comment by dfish3r** [comment]
We can't support a version for Java 1.6. I'm not even sure which features of Java 1.7 we're using, but it's not a terribly big project. Your best bet is to fork it and work through all the compile errors until you get a version that works.

**Comment by acevedodamian** [comment]
Thanks.  I did that, it wasn't hard , but it took time,  you are using a lot of  declarations like this ArrayList<>(); also a class called StandardCharsets, and some try catchs try-with-resources statements. Everything else worked fine.

thanks, 
Damian

**Comment by dfish3r** [comment]
If you can provide a link to your fork others may find it useful.
