### ISSUE TITLE
Change constructor of a PasswordValidator acording PECS princips.

### ISSUE THREAD

**Issue by foal** [vt-middleware/passay#55]
From 
```Java
public PasswordValidator(final List<Rule> rules)
``` 
to 
```Java
public PasswordValidator(final List<? super Rule> rules)
```
see for more information http://stackoverflow.com/questions/2723397/what-is-pecs-producer-extends-consumer-super

**Comment by dfish3r** [comment]
My reading of that thread lends me to believe that we're got a producer.
And the pattern should be List<? extends Rule>.

Is there a specific compile time problem you're trying to solve?

**Comment by foal** [comment]
Easy :)
```Java
private static final List<CharacterRule> RULES = ImmutableList.of(ucimpRule);
validator = new PasswordValidator(StreamEx.of(RULES).map(r -> (Rule) r).toList());
```

**Comment by foal** [comment]
And looks like you are right. It is a producer. So List<? extends Rule>.
