### ISSUE TITLE
CharacterRule, WhiteSpaceRule could use Javas Character class to support international

### ISSUE THREAD

**Issue by Jojs** [vt-middleware/passay#57]
Trying to allow international characters is possible by implementing CharacterData but alone basic latin contains 289 capital letters http://www.utf8-chartable.de/unicode-utf8-table.pl?number=1024
Getting indexOf for a complete list could become slow as implemented in PasswordUtils.getMatchingCharacters(..) - it is already iterating over chars in password so it would be easy to use the [Character class](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html) to answer if a char is this or that ... (see list below) with only one pass of the password.

It seems easy within the Basic Multilingual Plane (BMP), the set of characters from U+0000 to U+FFFF. Characters whose code points are greater than U+FFFF requires usage of the character's code point (I don't know if that is easy or relevant?)

## List of typical is's that Character Class could answer
- The specified character is an alphabetic.
- The specified character is a digit.
- The specified character is a letter.
- The specified character is a letter or digit.
- The specified character is a lowercase character.
- The specified character is an uppercase character.
- The specified character is whitespace according to Java.

Example analyze:
`
public class CharacterAnalyze {

    private int countAlphabetic;
    private int countDigit;
    private int countLetter;
    private int countLetterOrDigit;
    private int countLower;
    private int countUpper;
    private int countWhitespace;
    
    public void analyse(String input) {
        for(int i=0; i < input.length() ; i++) {
            Character ch = input.charAt(i);
            countAlphabetic += Character.isAlphabetic(ch) ? 1 : 0;
            countDigit += Character.isDigit(ch) ? 1 : 0;
            countLetter += Character.isLetter(ch) ? 1 : 0;
            countLetterOrDigit += Character.isLetterOrDigit(ch) ? 1 : 0;
            countLower += Character.isLowerCase(ch) ? 1 : 0;
            countUpper += Character.isUpperCase(ch) ? 1 : 0;
            countWhitespace += Character.isWhitespace(ch) ? 1 : 0;
        }
    }

   getCount...
   ...
}
`
As an alternative to count, it could collect matching chars as done in current CharacterRule.

Analyze once and match that against rules.

**Comment by dfish3r** [comment]
> Getting indexOf for a complete list could become slow as implemented

I suppose that's true. Do you have any metrics that demonstrate the performance difference? It feels like premature optimization, but I haven't done any analysis.

**Comment by dfish3r** [comment]
> Trying to allow international characters is possible by implementing CharacterData but alone basic latin contains 289 capital letters

We've strategically stuck with english qwerty characters for the default implementations. That's simply because we don't have enough experience with international character sets to say what would or would not make for good password rules.

**Comment by dfish3r** [comment]
> public class CharacterAnalyze

You should look at the 1.3.0-SNAPSHOT API. It provides a MatchBehavior to indicate contains, startsWith or endsWith. That will further complicate your analyse implementation.

**Comment by Jojs** [comment]
Fair points. It won't solve all needs.  My main interest was in supporting more than English and felt that this could be a possibility instead of copying EnglishCharacterData in order to make a Danish or Icelandic or ... suppose that your application is worldwide. You might still require a specific number of upper case letters but wants to allow the users to do so in their own locale.
Even if your application is directed to the Danish locale you might have users from all over the world, and perhaps they would like to use their native locale for a part of the password.
Making a Danish version is easy, I just need to copy EnglishCharacterData and add ÆØÅ,. So it is for multiple languages. I just thought that since Java already can tell if a character is upper case or digit or lower case, or white space, etc. , well it could be a simpler way to create rules of this type.

**Comment by dfish3r** [comment]
For better or worse, we've taken the approach that rules should be written to a specific audience, not the entire world.
Please contribute your Danish implementation. (against the 1.3.0 snapshot)
Perhaps once we get a few more of these some refactoring will be in order.
