### ISSUE TITLE
Untypeable password from documentation example

### ISSUE THREAD

**Issue by heruan** [vt-middleware/passay#74]
The documentation reports this example for password generation:

```java
List<CharacterRule> rules = Arrays.asList(
  // at least one upper-case character
  new CharacterRule(EnglishCharacterData.UpperCase, 1),

  // at least one lower-case character
  new CharacterRule(EnglishCharacterData.LowerCase, 1),

  // at least one digit character
  new CharacterRule(EnglishCharacterData.Digit, 1),

  // at least one symbol (special character)
  new CharacterRule(EnglishCharacterData.Special, 1));

PasswordGenerator generator = new PasswordGenerator();

// Generated password is 12 characters long, which complies with policy
String password = generator.generatePassword(12, rules);
```

which produces this kind of passwords:

- `₼„₨"9Mz₤`
- `H₭₣¨‚g50`
- `₤¶8₠>$Un`

which are pretty much un-typeable. It is not clear how to generate a password with special characters, but also typeable e.g. `aTha$ex!3`.

**Comment by dfish3r** [comment]
The characters in the password originate from the `CharacterData`. If you don't like the characters in `EnglishCharacterData.Special` you can supply your own implementation.

```
    PasswordGenerator generator = new PasswordGenerator();
    String password = generator.generatePassword(
      12,
      new CharacterRule(EnglishCharacterData.UpperCase, 1),
      new CharacterRule(EnglishCharacterData.LowerCase, 1),
      new CharacterRule(EnglishCharacterData.Digit, 1),
      new CharacterRule(new CharacterData() {
        @Override
        public String getErrorCode() {
          return EnglishCharacterData.Special.getErrorCode();
        }

        @Override
        public String getCharacters() {
          return "mycustomcharacters";
        }
      }, 1));
```

**Comment by heruan** [comment]
Thank you Daniel, I'll do it this way! This can be closed for me, but I'd suggest to clarify this use case in the docs.

**Comment by dfish3r** [comment]
Thanks @heruan.
That example predates the expansion of special characters, which added non-ascii characters.
I've never had a use case for including special characters in generated passwords, so I removed it from the example.

See b982c51109f6d1aefd643ccbebae6ba69c0a4ea4
