### ISSUE TITLE
Support BCryptHashBean

### ISSUE THREAD

**Issue by heruan** [vt-middleware/passay#76]
Cryptacular added `BCryptHashBean` (https://github.com/vt-middleware/cryptacular/issues/39), but I can't use it to construct a new `DigestHistoryRule`. How can I check a BCrypt password history to validate my passwords?

**Comment by dfish3r** [comment]
This will require an API change, but it's doable.
Waiting resolution of https://github.com/vt-middleware/cryptacular/pull/45

**Comment by dfish3r** [comment]
Fixed in latest 1.3.2-SNAPSHOT.
Note that latest cryptacular must be pulled down and installed.
