### ISSUE TITLE
HistoryRule failed message

### ISSUE THREAD

**Issue by juanavelez** [vt-middleware/passay#82]
When using the HistoryRule, it is normally to validate that a password does not match the N previous passwords. Normally the previous passwords are stored in a repository and the 0..N previous passwords are passed as the password data/references to the HistoryRule (or subclasses). However, there is no way to specify the actual N value, so the if the list size passed to validate is 1 but the actual N is 4 (Rule is don't match the four previous passwords but the user has only set one password so far), then the message reads: `Password matches one of 1 previous passwords.`

I think there should be a way for the HistoryRule(and subclasses) to indicate the actual N to be displayed in the message. If not set, then continue using the size of the password data/references

**Comment by dfish3r** [comment]
I can see the value here if you're using multiple HistoryRules.
However, if you have a single rule you can just hard code the number in your message properties.

**Comment by juanavelez** [comment]
I am sorry, I don't follow. The issue is that my business rule says the pwd can't match the previous 4 passwords, but if the customer logs in for the first time, the next time they change the pwd, there will be a single pwd in the history and if they use the same pwd, the message they're getting is "Password matches one of 1 previous passwords" and they end up thinking that the pwd can only be different from the previous one and not from the actual 4 ones.

**Comment by dfish3r** [comment]
There's no need to close the issue, I think the changes are useful.
I just wanted to point out they are unnecessary if you're using a single HistoryRule.
In the case of multiple history rules, you're changes would be required.

**Comment by juanavelez** [comment]
Sorry, I originally wrote a comment because I did not understand what you meant, then went to the code and found what you meant, and so I thought there was no need to keep it open. Please re-open if you think the issue is of any value. I also had a PR which I also closed.
