### ISSUE TITLE
Please reconsider CheckStyle configuration

### ISSUE THREAD

**Issue by amichair** [vt-middleware/passay#87]
Please reconsider. CheckStyle is a wonderful tool which I use on many other projects, but some of its configuration in Passay seems counter-productive to me. For example forcing all parameters and local variables to be final, I've never seen this prevent bugs anywhere and it does make the code more verbose for no good reason and the development more annoying needing to fix this all the time. Same goes for parameter assignment checks etc.

This and other style configurations also go against the common Java coding conventions (I don't have the stats to back that up, just a couple popular coding style guides from Sun or Google, but you just don't see those styles much), which makes it more difficult to work with than necessary for developers with a Java background.

As further evidence, there are some 50 checkstyle on/off comments scattered around the code to bypass it since it often just doesn't make sense, and other places where the code itself has been made more convoluted just to bypass those checks instead of simpler and cleaner code.

Please reconsider :-)

**Comment by ememisya** [comment]
This is more of a preference from your perspective wouldn't you say?  https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.12.4 mentions variables which are, "effectively final" which is determined during compile time from what I understand.  The ambiguity comes in when you introduce things like reflection.  Consider the following code:

```
public class Hello
{

  final String explicitlyFinal = "Hello, you KNOW I don't change";
  String effectivelyFinal = "Hello, I don't change";

  public static void main(String[] args)
  {
    for (final Field f : Hello.class.getDeclaredFields()) {
      if ((f.getModifiers() & java.lang.reflect.Modifier.FINAL) == java.lang.reflect.Modifier.FINAL) {
        System.out.println(f.getName() + " is final.");
      }
    }
  }
}
```

The output states that "explicitlyFinal" is final, and effectivelyFinal is not.  It lets the person using reflection get a better idea about the intentions of the programmer who wrote the code instead of determining if that's effectively the case or not.  This is why I'm not making a case for execution performance, but rather human readability and argue that using final modifiers where the variables are final improves code cleanliness.  It also lets you emphasize variables which are not explicitly final for people working with reflection.  For example, I may not want "args" to be final and signal that to anyone using reflection.  I may agree with you there that not all which can be final must be, but rather should be.  I think it's fine the way it is though.

**Comment by amichair** [comment]
First of all, thanks for the detailed response, it is appreciated.

The reflection argument may be relevant to fields (whose final modifier is not enforced in this project), but I was referring to final local variables and parameters, for which reflection is not relevant.

As you mentioned, I'm not saying you should never use them, but that the number of methods for which they are helpful in clarifying and maintaining the code is small and you should use finals if it helps, but most methods are short, simple, and straightforward and there it offers no readability advantage, but on the contrary, just makes the code more cluttered at best, or actually forces the code to have unnatural workarounds (either in the code structure and variables themselves, or via checkstyle on/off comments) and thus make it worse.

Of course it's ultimately a matter of perspective (guided by facts, statistics and experience) and you have the last word :-)

btw another checkstyle rule I think hurts the code more than it helps is disallowing method parameters to have the same name as class fields - in particular, a constructor that receives parameters which are then assigned to the instance fields (which is what constructors usually do). In this case you have a perfectly good name for the data item, and you are forced to pick a second name, which in most cases is less ideal. Both the worse name and the duplicity of names for the same data item lower the quality of the code imho.

I'm just making a rational argument for why these particular checks are (in my opinion) making the code more cluttered and not more clear in most cases. So I asked for you to consider whether mandatory enforcement of them is indeed the best choice, or perhaps allowing them to be used with discretion is the better option - they should be used where they are helpful, but not forced where they degrade the code in some way.

**Comment by dfish3r** [comment]
We use checkstyle across all our Java projects, which include both applications and general purpose libraries. Having a consistent rule set helps our devs to produce conformant code on multiple projects. I've seen the FinalLocalVariable and HiddenField rules you're referring to prevent more than one bug from both junior and senior developers. The most common case occurring during IDE refactoring, when a variable is renamed and inadvertently produces myVariable = myVariable.

We do have slight variances on every project and devs can make compelling cases for why rules should be changes. In this case passay disables checks in 20 cases and 17 of those are in the `TernaryTree` implementation. So I think you bore the brunt of the pain in an implementation that requires us to run afoul of the rules that generally serve us well. I'm happy to consider PRs that tweak the rules, but I would not be inclined to remove checkstyle entirely.

As an aside, I do expect these rules to get more updates as we move to Java 11 and likely adopt a more functional style of programming with Java in general.

**Comment by amichair** [comment]
Well if it helps your devs and is consistent across your multiple projects, then let it be.

I did not mean to disable checkstyle entirely, just to tune the rules... I've used it and encountered it on many other projects as well, just with a more balanced and conventional set of rules (for my own definition of these terms ;-) ).

fwiw, I don't remember if Eclipse does it as well, but IntelliJ warns of self assignments as in the example you gave, so you can enjoy both normal and consistent parameter/field naming and no bugs of this sort. Maybe your IDE or other static analysis tools (is FindBugs still a thing?) can be used to find these bugs directly, without using code style workarounds to try to prevent them, so you can enjoy a win-win.

I'll close the issue and let you think about these rules and trade-offs at your own time. I'll just say that after many years and many projects, which are not related to each other in any way and most of which I had nothing to do with the enforced checkstyle rules, this one feels (subjectively) particularly more annoying / less productive to work on and contribute to due to the specific set of checkstyle rules being enforced. Enough to spend the time opening an issue about it :-) Perhaps you can factor that into your pros and cons when you get to it...

Thanks for your elaborate responses, in any case!
